webapp/app/main/forms.py
from flask import url_for, current_app

from flask_wtf import FlaskForm, RecaptchaField
from flask_wtf.file import FileField, FileAllowed
from wtforms import ValidationError
from wtforms.fields import (
    StringField,
    SubmitField,
    SelectField,
    HiddenField,
    BooleanField,
    IntegerField
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length, DataRequired, Email, URL, Optional

from app.models import Mole, User, Sex, Ancestry, History, NumNaevi
from app import imageSet

class MoleForm(FlaskForm):
    sex = SelectField(
        'Sex', coerce=int,
        validators=[InputRequired()],
        choices=[(i, v) for i, v in enumerate(Sex.values)])

    age = StringField('Age', validators=[InputRequired()])

    ancestry = SelectField(
        'Ancestry', coerce=int,
        validators=[Optional()],
        choices=[(i, v) for i, v in enumerate(Ancestry.values)])
    
    body_location = StringField(description="NONE", validators=[InputRequired()])
    body_image = StringField(description="NONE", validators=[InputRequired()])

    num_moles = IntegerField(description="NONE", default=1, validators=[InputRequired()])

    personal_history = SelectField(
        'Personal history of melanoma',
        validators=[Optional()], coerce=int,
        choices=[(i, v) for i, v in enumerate(History.values)])

    family_history = SelectField(
        'Family history of melanoma',
        validators=[Optional()], coerce=int,
        choices=[(i, v) for i, v in enumerate(History.values)])

    image = FileField(validators=[FileAllowed(imageSet, 'Images only!')], render_kw={"accept": "image/*", "capture": "environment"})

    
    geo_suburb = StringField("Suburb", validators=[Optional()])
    geo_state = StringField("State", validators=[Optional()])
    geo_long = StringField()
    geo_lat = StringField()

    contact_research = BooleanField(default=False)
    name = StringField("Name")
    dob = StringField("Date of Birth")
    email = EmailField("Email address", validators=[Optional(), Email()])

    pathology = StringField('Pathology', validators=[Optional()])
    number_naevi = SelectField(
        'Number of moles',
        validators=[Optional()], coerce=int,
        choices=[(i, v) for i, v in enumerate(NumNaevi.values)])

    submit = SubmitField('Submit')

webapp/app/main/__init__.py
from app.main import errors  # noqa
from app.main.views import main # noqa

webapp/app/main/views.py
from flask import Blueprint, render_template, jsonify, current_app

from app.models import EditableHTML, Mole
from .forms import MoleForm
from app import db
from werkzeug.utils import secure_filename
import logging, string, random, os

logger = logging.getLogger("DaM")


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')


@main.route('/about')
def about():
    editable_html_obj = EditableHTML.get_editable_html('about')
    return render_template(
        'main/about.html', editable_html_obj=editable_html_obj)

@main.route('/privacy')
def privacy():
    editable_html_obj = EditableHTML.get_editable_html('privacy')
    return render_template(
        'main/privacy.html', editable_html_obj=editable_html_obj)

def randStr(stringLength=10):
  letters = string.ascii_lowercase
  return ''.join(random.choice(letters) for i in range(stringLength))

@main.route('/share')
def share():
  return render_template('main/index.html')

@main.route('/donate', methods=["GET", "POST"])
def donate():
    form = MoleForm()
    if form.validate_on_submit():
        f = form.image.data
        filename = secure_filename(f.filename)
        logger.info(filename)
        filename = randStr(12) + filename
        fpath = os.path.join(current_app.instance_path, '../app/static/uploads/moles', filename)
        logger.info(filename)
        logger.info(fpath)
        f.save(fpath)
        mole = Mole()
        form.populate_obj(mole)
        mole.image_path=filename
        db.session.add(mole)
        db.session.commit()

        return render_template(
        'main/thankyou.html')
    return render_template(
        'main/donate.html', form=form)

    

webapp/app/templates/main/about.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="Site-content ui text container">
        <h2>About</h2>
        <p>donate a mole is a citizen science project to improve early detection of melanoma. The incidence rates of melanoma in Australia is 12 times the global average, and it is the most common cancer in Australians aged 18 to 39 years.</p>

        <p>A citizen scientist is a person who helps researchers gather or interpret data, especially for large data sets that would have been impossible to collect or sift through in the past. We need your help to collect as many moles and their locations to create the hotspot map.</p>

        <p>The University of Queensland Dermatology Research Centre is a world leading team of researchers studying skin cancer. We aim to empower Australians to become citizen scientists by using the tool that everyone has in their back pocket, their mobile phone. By donating a mole, we hope to increase an awareness of skin cancer risk, while contributing to our world-renowned research program. The images will form an image database of moles and melanomas that will assist researchers in identifying melanoma hotspots.</p>
        
        <p>donate a mole is an open-source application developed at HealthHack Brisbane 2019.</p>

        <a href="{{ url_for('main.donate') }}">
            <div class="ui primary fluid button">donate a mole</div>
          </a>

          <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
                <a href="{{ url_for('main.privacy') }}">
                    <div id="footerBtnS" class="ui primary fluid button dam secondary">privacy policy</div>
                  </a>
            </footer>
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

webapp/app/templates/main/donate.html
{% import 'macros/page_macros.html' as page %}
{% import 'macros/form_macros.html' as f %}
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="Site-content ui text container">
      <noscript>You need to enable JavaScript to run this app.</noscript>

      {% if form.errors %}
        {{ form.errors }}
      {% endif %}

      <div id="bodyLocRoot">
        <h2>Hotspot your mole</h2>
        <div id="donateRoot"></div>
      </div>
      
      
      {% set flashes = {
          'error':   get_flashed_messages(category_filter=['form-error']),
          'warning': get_flashed_messages(category_filter=['form-check-email']),
          'info':    get_flashed_messages(category_filter=['form-info']),
          'success': get_flashed_messages(category_filter=['form-success'])
      } %}

      {{ f.begin_form(form, flashes) }}

      <div class="hiddendiv">
          {{ f.render_form_field(form.image) }}
          {{ f.render_form_field(form.contact_research) }}
      </div>

      <div class="moletab 0">
        <h2>info</h2>
        <p>We are mapping melanoma hotspots on the body to improve detection of Australia’s national cancer</p>
            <p>Step one- take a photo of a mole on your skin</p>
            <p>Step two- map the location of the mole on your body</p>
            <p>Get started and become a citizen scientist to fight melanoma you must be 18 years or older participate</p>
        </p>
      </div>

      <div class="moletab 1">
        <h2>take a picture</h2>
        <p>Hold your phone about 20 cm from your mole When photographing the skin, orient the camera horizontally</p>
        <img class="ui fluid" id="imgpreview" src="#" alt="Upload a mole to preview" />
      </div>

      <div class="moletab 2 bodyTab">
        
        {{ f.render_form_field(form.body_location) }}
        {{ f.render_form_field(form.body_image) }}
      </div>

      <div class="moletab 3">
        <h2>add another mole</h2>
        {{ f.render_form_field(form.num_moles) }}
      </div>

      <div class="moletab 4">
        <h2>help us complete the picture</h2>
        {{ f.render_form_field(form.age) }}
        {{ f.render_form_field(form.sex) }}
        {{ f.render_form_field(form.geo_suburb) }}
        {{ f.render_form_field(form.geo_state) }}
        {{ f.render_form_field(form.ancestry) }}

      </div>

      <div class="moletab 5">
          <h2>almost there!</h2>

          {{ f.render_form_field(form.personal_history) }}
          {{ f.render_form_field(form.family_history) }}
          {{ f.render_form_field(form.pathology) }}
          {{ f.render_form_field(form.number_naevi) }}
  
        </div>

      <div class="moletab 6">
        <h2>consent</h2>
        <p>I give permission for my doctors, other health professionals, hospitals, Queensland Cancer Registry or pathology laboratories outside to release information, for example pathology reports, to the University of Queensland concerning my lesion excision that is needed for this project. Additionally, I give my permission to Queensland Cancer Registry to release pathology reports regarding my previous melanoma diagnosis and other types of invasive cancers.</p>
      </div>

      <div class="moletab 7">
        <h2>consent</h2>
        <p>Contact details</p>
        {{ f.render_form_field(form.name) }}
        {{ f.render_form_field(form.dob) }}
        {{ f.render_form_field(form.email) }}
      </div>

      <div class="moletab 8">
        
      </div>

      {{ f.end_form(form) }}
          
    </div>
  </div>

  <div id="status-area"></div>
  <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
    <div class="ui text container">
        <button id="footerBtnSec" onclick="nextProcessSec()" class="ui primary fluid button">Next</button>
      <button id="footerBtn" onclick="nextProcess()" class="ui primary fluid button">Next</button>
    </div>
  </footer>
  <!-- Circles which indicates the steps of the form: -->
  <footer style="text-align:center;margin-top:10px;margin-bottom:40px;">
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
  </footer>
<!-- jquery flash message hack -->
<script>
    (function($) {
      $.fn.flash_message = function(options) {
        
        options = $.extend({
          text: 'Done',
          time: 1000,
          how: 'before',
          class_name: ''
        }, options);
        
        return $(this).each(function() {
          if( $(this).parent().find('.flash_message').get(0) )
            return;
          
          var message = $('<span />', {
            'class': 'flash_message ' + options.class_name,
            text: options.text
          }).hide().fadeIn('fast');
          
          $(this)[options.how](message);
          
          message.delay(options.time).fadeOut('normal', function() {
            $(this).remove();
          });
          
        });
      };
  })(jQuery);
</script>

<script>
  var currentTab = 0; // Current tab is set to be the first tab (0)
  prepTab(currentTab); // Display the current tab
  var footerBtnSecHidden = true;

  function attachImageChange() {
    $('#image').on("change", function(){ 
      console.log("image on change");
      var testImage = $('#image').val();
      if (testImage) {
        resetImage = false;
        $("#footerBtn").html('submit photo');
        $("#footerBtnSec").html('retake photo');
        if (footerBtnSecHidden) {
          $("#footerBtnSec").transition('fade', '500ms');
          footerBtnSecHidden = false;
        }
      }
    });
  }

  attachImageChange();

  $('.locatorImage').on('click', function(){ 
    console.log("locatorImage on click");
    var molePointer = document.querySelector(".pointer");
      molePointer.style.display = "block";
  });

  var resetImage = true;

  function nextProcessSec() {
    switch (currentTab) {
      case 1:
        $('#image').trigger('click'); 
        break
      case 3:
        resetImage = true;
        $('#body_location').removeAttr('value');
        $('#imgpreview').removeAttr('src');
        
        var molePointer = document.querySelector(".pointer");
        //molePointer.style.display = "none";
        
        $("#footerBtn").html('photo of your mole');
        $("#footerBtnSec").transition('fade', '500ms');
        footerBtnSecHidden = true;
        
        nextPrev(-2)
        break
      case 6:
        $('.ui.form').submit();
        $("#footerBtn").html('return home');
        $("#footerBtnSec").transition('fade', '500ms');
        footerBtnSecHidden = true;
        nextPrev(2)
        break
    }
  }

  function nextProcess() {
    console.log("currentTab: " + currentTab);
    switch (currentTab) {
      case 0:
        $("#footerBtn").html('photo of your mole');
        nextPrev(1)
        break
      case 1:
        if (resetImage) {
          $('#image').trigger('click');
        } else {
          $("#footerBtn").html('confirm mole hotspot');
          $("#footerBtnSec").transition('fade', '500ms');
          footerBtnSecHidden = true;
          nextPrev(1)          
        }
        break
      case 2:
        var bLoc = $("#body_location").val();
        if (bLoc) {
          console.log("bloc: " + bLoc);
          $("#bodyLocRoot").transition('horizontal flip', '100ms');
          $("#footerBtn").html('proceed');

          $("#footerBtnSec").html('donate another mole');
          $("#footerBtnSec").transition('fade', '500ms');
          footerBtnSecHidden = false;

          nextPrev(1);
        } else {
          $('#status-area').flash_message({
            text: 'Please select a mole location',
            how: 'append'
        });
      }
        break
      case 3:
        $("#footerBtnSec").transition('fade', '500ms');
        footerBtnSecHidden = true;

        $("#footerBtn").html('next');
        nextPrev(1)
        break
      case 4:
        var ageVal = $("#age").val(); 
        if ((ageVal) && ($.isNumeric(ageVal)) && (ageVal>=18)) {
          $("#footerBtn").html('next');
          nextPrev(1)
        } else if ((ageVal) && ($.isNumeric(ageVal)) && (ageVal<18)) {
          $('#status-area').flash_message({
            text: 'Sorry, you have to be 18+',
            how: 'append'
          });
        } else if ((ageVal) && !($.isNumeric(ageVal))) {
          $('#status-area').flash_message({
            text: 'Please enter a number for age',
            how: 'append'
          });
        } else {
          $('#status-area').flash_message({
            text: 'Please enter your age to continue',
            how: 'append'
          });
        }
        break
      case 5:
        $("#footerBtn").html('I agree: contact me');

        $("#footerBtnSec").html('I disagree: donate moles anonymously');
        $("#footerBtnSec").transition('fade', '500ms');
        footerBtnSecHidden = false;

        nextPrev(1)
        break
      case 6:
        $("#footerBtn").html('donate moles!');
        $("#contact_research").prop('checked', true);
        
        $("#footerBtnSec").transition('fade', '500ms');
        footerBtnSecHidden = true;

        nextPrev(1)
        break
      case 7:
        $('.ui.form').submit();
        $("#footerBtn").html('return home');
        nextPrev(1)
        break
      case 8:
        window.location.href = "{{ url_for('main.index') }}";
        break
    }
  }

  function prepTab(n) {
    $(".moletab."+n)
      .transition('horizontal flip', '500ms')
      .delay(1000)
    ;
    fixStepIndicator(n)
  }

  function showTab(n) {
    // This function will display the specified tab of the form ...
    $(".moletab."+n)
      .delay(2000)
      .transition('horizontal flip', '500ms')
    ;
    if (n == 2) $("#bodyLocRoot")
      .transition('horizontal flip', '100ms')
    ;
    fixStepIndicator(n)
  }

  function nextPrev(n) {
    // This function will figure out which tab to display
    var x = document.getElementsByClassName("moletab");

    $(".moletab."+currentTab)
      .transition('horizontal flip')
    ;
    
    currentTab = currentTab + n;

    if (currentTab >= x.length) {
      return false;
    }

    showTab(currentTab);
  }

  function fixStepIndicator(n) {
    var i, x = document.getElementsByClassName("step");
    for (i = 0; i < x.length; i++) {
      x[i].className = x[i].className.replace(" active", "");
    }

    for (i = 0; i < n; i++) {
      x[i].className += " active";
    }
  }
</script>

<script>
    function previewImg(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function(e) {
          $('#imgpreview').attr('src', e.target.result);
        }
        
        reader.readAsDataURL(input.files[0]);
      }
    }
    
    $("#image").change(function() {
      previewImg(this);
    });
</script>
<script src="{{ url_for('static', filename='donate/donate_bundle.js') }}"></script>
{% endblock %}

webapp/app/templates/main/index.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div class="Site-content ui text container">
      <h2>get started</h2>

      <p>donate a mole is a citizen science project to improve early detection of melanoma.</p>

          <p>The incidence rates of melanoma in Australia is 12 times the global average, and it is the most common cancer in Australians aged 18 to 39 years.</p>
          
        <p>Melanomas can occur anywhere on the body, help us find the hotspots.</p>

      <a href="{{ url_for('main.donate') }}">
        <div class="ui primary fluid button">donate a mole</div>
      </a>
      <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
          <a href="{{ url_for('main.about') }}">
              <div style="display:block;" id="footerBtnSec" class="ui primary fluid button dam secondary">about us</div>
            </a>
            <a href="{{ url_for('main.privacy') }}">
                <div id="footerBtnS" class="ui primary fluid button dam secondary">privacy policy</div>
              </a>
              <br></br>
              <p>This app is for research purposes only. It does not provide medical advice. If you have any concerns about your moles or any health issue please consult your general practitioner or other healthcare professional.</p>
        </footer>
        
      </a>
    </div>
{% endblock %}

webapp/app/templates/main/privacy.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="Site-content ui text container">
        <h2>Privacy Policy</h2>
        <p>donate a mole is bound by Commonwealth and State privacy legislation, including the Privacy Act 1988 (Commonwealth) and the Information Privacy Act 2009 (Queensland). In addition, the application must adhere to the guidelines of the National Health and Medical Research Council of Australia, Medicare Australia and is also accountable to the University of Queensland-Human Research Ethics Committee.</p>

        <a href="{{ url_for('main.donate') }}">
            <div class="ui primary fluid button">donate a mole</div>
          </a>

        <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
            <a href="{{ url_for('main.about') }}">
                <div style="display:block;" id="footerBtnSec" class="ui primary fluid button dam secondary">about us</div>
              </a>
          </footer>
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

webapp/app/templates/main/share.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="Site-content ui text container">
    <h2>thank you</h2>
    <p>Thank you for contributing towards the fight against skin cancer</p>
    <h2>share</h2>
    <p>Help spread awareness of skin cancer and contribute to research by sharing donate-a-mole on social media</p>

    <div class="ui grid socialgrid">

      <a class="four wide column" href="https://www.facebook.com/sharer/sharer.php?u=https://donateamole.org/share">
        <div class="ui facebook button">
          <i class="facebook icon"></i>
        Facebook
        </div>
      </a>
      
      <a class="four wide column" href="https://twitter.com/home?status=https://donateamole.org/share I've joined the fight to beat melanoma - and you can do too #donateamole #citizenscience">
        <div class="ui twitter button">
          <i class="twitter icon"></i>
          Twitter
        </div>
      </a>
      
      <a class="four wide column" href="https://www.linkedin.com/shareArticle?mini=true&url=https://donateamole.org/share&title=&summary=I've joined the fight to beat melanoma - and you can do too #donateamole #citizenscience&source=">
        <div class="ui linkedin button">
          <i class="linkedin icon"></i>
          LinkedIn
        </div>
      </a>
      
      <a class="four wide column" href="mailto:info@examplescom?&cc=&bcc=&subject=Donate a mole for melanoma research&body=I've joined the fight to beat melanoma - and you can do too https://donateamole.org/share">
        <div class="ui instagram button">
          <i class="envelope icon"></i>
          Send Email
        </div>
      </a>
      </div>
    

        <a href="{{ url_for('main.donate') }}">
            <div class="ui primary fluid button">donate a mole</div>
          </a>

        <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
            <a href="{{ url_for('main.about') }}">
                <div style="display:block;" id="footerBtnSec" class="ui primary fluid button dam secondary">about us</div>
              </a>
          </footer>
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

webapp/app/templates/main/thankyou.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
<div class="Site-content ui text container">
    <h2>thank you</h2>
    <p>Thank you for contributing towards the fight against skin cancer</p>
    <h2>share</h2>
    <p>Help spread awareness of skin cancer and contribute to research by sharing donate-a-mole on social media</p>

    <div class="ui grid socialgrid">

      <a target="_blank" class="four wide column" href="https://www.facebook.com/sharer/sharer.php?u=https://donateamole.org/share">
        <div class="ui facebook button">
          <i class="facebook icon"></i>
        Facebook
        </div>
      </a>
      
      <a target="_blank" class="four wide column" href="https://twitter.com/home?status=https://donateamole.org/share I've joined the fight to beat melanoma - and you can do too #donateamole #citizenscience">
        <div class="ui twitter button">
          <i class="twitter icon"></i>
          Twitter
        </div>
      </a>
      
      <a target="_blank" class="four wide column" href="https://www.linkedin.com/shareArticle?mini=true&url=https://donateamole.org/share&title=&summary=I've joined the fight to beat melanoma - and you can do too #donateamole #citizenscience&source=">
        <div class="ui linkedin button">
          <i class="linkedin icon"></i>
          LinkedIn
        </div>
      </a>
      
      <a target="_blank" class="four wide column" href="mailto:info@examplescom?&cc=&bcc=&subject=Donate a mole for melanoma research&body=I've joined the fight to beat melanoma - and you can do too https://donateamole.org/share">
        <div class="ui instagram button">
          <i class="envelope icon"></i>
          Send Email
        </div>
      </a>
      </div>
    

        <a href="{{ url_for('main.donate') }}">
            <div class="ui primary fluid button">donate a mole</div>
          </a>

        <footer style="text-align:center;margin-top:40px;margin-bottom:10px;">
            <a href="{{ url_for('main.about') }}">
                <div style="display:block;" id="footerBtnSec" class="ui primary fluid button dam secondary">about us</div>
              </a>
          </footer>
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}